require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SubtypesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Subtype. As you add validations to Subtype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubtypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all subtypes as @subtypes" do
      subtype = Subtype.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:subtypes)).to eq([subtype])
    end
  end

  describe "GET #show" do
    it "assigns the requested subtype as @subtype" do
      subtype = Subtype.create! valid_attributes
      get :show, {:id => subtype.to_param}, valid_session
      expect(assigns(:subtype)).to eq(subtype)
    end
  end

  describe "GET #new" do
    it "assigns a new subtype as @subtype" do
      get :new, {}, valid_session
      expect(assigns(:subtype)).to be_a_new(Subtype)
    end
  end

  describe "GET #edit" do
    it "assigns the requested subtype as @subtype" do
      subtype = Subtype.create! valid_attributes
      get :edit, {:id => subtype.to_param}, valid_session
      expect(assigns(:subtype)).to eq(subtype)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Subtype" do
        expect {
          post :create, {:subtype => valid_attributes}, valid_session
        }.to change(Subtype, :count).by(1)
      end

      it "assigns a newly created subtype as @subtype" do
        post :create, {:subtype => valid_attributes}, valid_session
        expect(assigns(:subtype)).to be_a(Subtype)
        expect(assigns(:subtype)).to be_persisted
      end

      it "redirects to the created subtype" do
        post :create, {:subtype => valid_attributes}, valid_session
        expect(response).to redirect_to(Subtype.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved subtype as @subtype" do
        post :create, {:subtype => invalid_attributes}, valid_session
        expect(assigns(:subtype)).to be_a_new(Subtype)
      end

      it "re-renders the 'new' template" do
        post :create, {:subtype => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subtype" do
        subtype = Subtype.create! valid_attributes
        put :update, {:id => subtype.to_param, :subtype => new_attributes}, valid_session
        subtype.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested subtype as @subtype" do
        subtype = Subtype.create! valid_attributes
        put :update, {:id => subtype.to_param, :subtype => valid_attributes}, valid_session
        expect(assigns(:subtype)).to eq(subtype)
      end

      it "redirects to the subtype" do
        subtype = Subtype.create! valid_attributes
        put :update, {:id => subtype.to_param, :subtype => valid_attributes}, valid_session
        expect(response).to redirect_to(subtype)
      end
    end

    context "with invalid params" do
      it "assigns the subtype as @subtype" do
        subtype = Subtype.create! valid_attributes
        put :update, {:id => subtype.to_param, :subtype => invalid_attributes}, valid_session
        expect(assigns(:subtype)).to eq(subtype)
      end

      it "re-renders the 'edit' template" do
        subtype = Subtype.create! valid_attributes
        put :update, {:id => subtype.to_param, :subtype => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @subtype = @user.subtypes.last
    end

    describe 'unauthenticated' do
      it 'return 401' do
        sign_in nil
        delete :destroy, { id: @subtype.to_param, format: :json }
        expect(response).to have_http_status(:unauthorized)
      end
    end

    describe 'authenticated as other user/user does not own subtype' do
      it 'return 400' do
        sign_in FactoryGirl.create(:user)
        delete :destroy, { id: @subtype.to_param, format: :json}
        expect(response).to have_http_status(:bad_request)
      end
    end

    describe 'authenticated' do
      it "destroys the requested subtype" do
        sign_in @user
        expect {
          delete :destroy, { id: @subtype.to_param, format: :json }
        }.to change(Subtype, :count).by(-1)

        require 'json'
        deleted_subtype = JSON.parse(response.body)
        expect(deleted_subtype['id']).to be(@subtype.id)
        expect(response).to have_http_status(:ok)
      end
    end
  end
end
