require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TypesController, type: :controller do
  let(:invalid_attributes) {
    { something: 'abc'}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @types = @user.types
    end
    
    describe "authenticated" do
      it "assigns all types as @types" do
        sign_in @user 
        get :index
        expect(assigns(:types)).to eq(@types)
        expect(response).to render_template('types/_index')
      end
    end
    
    describe "unauthenticated" do
      it 'redirects to sign in page' do
        sign_in nil
        get :index
        expect(response).to redirect_to '/users/sign_in'
      end
    end
  end

  describe "GET #show" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @type = @user.types.first
    end
    
    describe "authenticated" do
      it "assigns the requested type as @type" do
        sign_in @user 
        get :show, {id: @type.to_param}
        expect(assigns(:type)).to eq(@type)
        expect(response).to render_template(:show)
      end
    end

    describe "authenticated as other user" do
      it 'redirects to sign in page' do 
        sign_in FactoryGirl.create(:user)
        get :show, {id: @type.to_param}
        expect(response).to redirect_to '/users/sign_in'
      end
    end
    
    describe "unauthenticated" do
      it 'redirects to sign in page' do
        sign_in nil
        get :show, {id: @type.to_param}
        expect(response).to redirect_to '/users/sign_in'
      end
    end
  end

  describe "GET #new" do
    describe "authenticated" do
      it "assigns a new type as @type" do
        sign_in
        get :new
        expect(assigns(:type)).to be_a_new(Type)
        expect(response).to render_template(:new)
      end
    end

    describe "unauthenticated" do
      it 'assigns a new type as @type' do
        sign_in nil
        get :new
        expect(assigns(:type)).to be_a_new(Type)
        expect(response).to render_template(:new)
      end
    end
  end

  describe "GET #edit" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @type = @user.types.first
    end
    
    describe "authenticated" do
      it "assigns the requested type as @type" do
        sign_in @user
        get :edit, { id: @type.to_param }
        expect(assigns(:type)).to eq(@type)
        expect(response).to render_template('types/_edit')
      end
    end

    describe "authenticated as other user" do
      it 'redirects to sign in page' do
        sign_in FactoryGirl.create(:user)
        get :edit, { id: @type.to_param }
        expect(response).to redirect_to '/users/sign_in'
      end
    end
    
    describe "unauthenticated" do
      it 'redirects to sign in page' do
        sign_in nil
        get :edit, { id: @type.to_param}
        expect(response).to redirect_to '/users/sign_in'
      end
    end
  end

  describe "POST #create" do
    describe 'unauthenticated' do
      it 'redirects to sign up page' do
        sign_in nil
        type = FactoryGirl.build(:type)
        expect { post :create, type: type.attributes }.to change(Type, :count).by(0)
        expect(response).to redirect_to new_user_session_url
      end
    end

    describe 'authenticated' do
      before(:each) do
        @user = FactoryGirl.create(:user)
        @type = FactoryGirl.build(:type)
        sign_in @user
      end

      describe 'with valid params' do
        it 'creates a new type' do
          expect { post :create, type: @type.attributes, format: :json }.to change(Type, :count).by(1)
        end

        it "assigns a newly created type as @type" do
          post :create, { type: @type.attributes, format: :json }
          expect(assigns(:type)).to be_a(Type)
          expect(assigns(:type)).to be_persisted
        end

        it "responds with newly created type" do
          post :create, { type: @type.attributes, format: :json }
          require 'json'
          type = JSON.parse(response.body)
          expect(response).to have_http_status(:created)
          expect(type['name']).to eq(@type.name)
        end
      end

      describe 'with invalid params' do
        it "assigns a newly created but unsaved type as @type" do
          post :create, { type: invalid_attributes, format: :json }
          expect(assigns(:type)).to be_a_new(Type)
        end

        it "returns errors" do
          post :create, { type: invalid_attributes, format: :json }
          require 'json'
          errors = JSON.parse(response.body)
          expect(errors).to include('name')
          expect(response).to have_http_status(:unprocessable_entity)
        end
      end
    end
  end

  describe "PUT #update" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @type = @user.types.first
      @new_attributes = { name: "fur_#{Time.now}"}
    end

    describe 'unauthenticated' do
      it 'redirects to sign up page' do
        sign_in nil
        put :update, { id: @type.to_param, type: @new_attributes, format: :json }
        expect(response).to redirect_to new_user_session_url
      end
    end

    describe 'authenticated as other user' do
      it 'redirects to sign up page' do
        sign_in FactoryGirl.create(:user)
        put :update, { id: @type.to_param, type: @new_attributes, format: :json }
        expect(response).to redirect_to new_user_session_url
      end
    end

    describe 'authenticated' do
      before(:each) do
        sign_in @user
      end

      describe "with valid params" do
        it "updates the requested type" do
          put :update, { id: @type.to_param, type: @new_attributes, format: :json }
          require 'json'
          type = JSON.parse(response.body)
          expect(type['name']).to eq(@new_attributes[:name])
          expect(response).to have_http_status(:ok)
        end

        it "assigns the requested type as @type" do
          put :update, { id: @type.to_param, type: @new_attributes, format: :json }
          expect(assigns(:type)).to eq(@type)
        end
      end

      describe "with invalid params" do
        it "assigns the type as @type" do
          put :update, { id: @type.to_param, type: { name: '' }, format: :json }
          expect(assigns(:type)).to eq(@type)
        end

        it "returns errors" do
          put :update, { id: @type.to_param, type: { name: '' }, format: :json }
          require 'json'
          errors = JSON.parse(response.body)
          expect(errors).to include('errors')
          expect(response).to have_http_status(:ok)
        end
      end
    end
  end

  describe "DELETE #destroy" do
    before(:each) do
      @user = FactoryGirl.create(:user)
      @type = @user.types.first
    end

    describe 'unauthenticated' do
      it 'redirects to sign up page' do
        sign_in nil
        delete :destroy, { id: @type.to_param, format: :json }
        expect(response).to redirect_to new_user_session_url
      end
    end

    describe 'authenticated as other user' do
      it 'redirects to sign up page' do
        sign_in FactoryGirl.create(:user)
        delete :destroy, { id: @type.to_param, format: :json}
        expect(response).to redirect_to new_user_session_url
      end
    end

    describe 'authenticated' do
      it "destroys the requested type" do
        sign_in @user
        expect {
          delete :destroy, { id: @type.to_param, format: :json }
        }.to change(Type, :count).by(-1)

        require 'json'
        deleted_type = JSON.parse(response.body)
        expect(deleted_type['id']).to eq(@type.id)
        expect(response).to have_http_status(:ok)
      end
    end
  end
end